### ISSUE TITLE
Return all tried results from all calibration methods (RM-14682)

### ISSUE THREAD

**Issue by pmaner** [jmp75/metaheuristics#11]
On completion, the Calibration Runner should display the history of objective function & metaparameter values used during the optimisation process.
The calibration history is working for SCE and SCE & Rosenbrock but the other optimisation algorithms only display the best (or last?) optimisation result.

The returned results from evolve() call are an array and it makes sense to return all the results tried ordered so the first one is the best (and for backward compatibility)

proposed fix in
https://github.com/jmp75/metaheuristics/pull/10

**Comment by jmp75** [comment]
Pull request merged.
